name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout #1
        uses: actions/checkout@v3 #Task from external provider

      - name: Install dependencies
        run: | #Run commands
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: | #Run commands
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app